# This is a basic workflow to help you get started with Actions

name: Publish Update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Push Timestamp to File
        run: |
          git config --global user.name 'AlexDev404'
          git config --global user.email 'alexdev404@users.noreply.github.com'
          git fetch
          rm update_ts
          date +%s >> update_ts
          git add .
          git commit -am "Publish Update"
          git fetch --all
          git push origin main
